name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python and Poetry
        uses: ./.github/workflows/setup.yaml
        with:
          python-version: '3.12'

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --show-diff-on-failure --color=always --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python and Poetry
        uses: ./.github/workflows/setup.yaml
        with:
          python-version: '3.12'
#     Uncomment this line when first tests appear
#      - name: Run Tests
#        run: |
#          poetry run pytest tests
